apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::633897975342:role/UdacityFlaskDeployCBKubectlRole
      username: build

  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::633897975342:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17IB8DGLNFM02
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-20T01:27:36Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-20T01:27:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1278"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 997ebcc6-1186-4004-b927-4a0da9338482
